# -*- coding: utf-8 -*-
from Blender.Draw import *

BLENDER_KEYS = {
    #'accent': Draw.ACCENTGRAVEKEY,
    'backslash': BACKSLASHKEY,
    'backspace': BACKSPACEKEY,
    'capslock': CAPSLOCKKEY,
    'del': DELKEY,
    'down_arrow': DOWNARROWKEY,
    'end': ENDKEY,
    '=': EQUALKEY,
    'esc': ESCKEY,
    'f10': F10KEY,
    'f11': F11KEY,
    'f12': F12KEY,
    'f1': F1KEY,
    'f2': F2KEY,
    'f3': F3KEY,
    'f4': F4KEY,
    'f5': F5KEY,
    'f6': F6KEY,
    'f7': F7KEY,
    'f8': F8KEY,
    'f9': F9KEY,
    'home': HOMEKEY,
    #'': INPUTCHANGE,
    'insert': INSERTKEY,
    #'': KEYBD,
    'left_alt': LEFTALTKEY,
    'left_arrow': LEFTARROWKEY,
    #'': LEFTBRACKETKEY, # which bracket?
    'left_ctrl': LEFTCTRLKEY,
    'left_mouse': LEFTMOUSE,
    'left_shift': LEFTSHIFTKEY,
    'linefeed': LINEFEEDKEY,
    'middle_mouse': MIDDLEMOUSE,
    'minus': MINUSKEY,
    'mouse_x': MOUSEX,
    'mouse_y': MOUSEY,
    'numpad_0': PAD0,
    'numpad_1': PAD1,
    'numpad_2': PAD2,
    'numpad_3': PAD3,
    'numpad_4': PAD4,
    'numpad_5': PAD5,
    'numpad_6': PAD6,
    'numpad_7': PAD7,
    'numpad_8': PAD8,
    'numpad_9': PAD9,
    'numpad_*': PADASTERKEY,
    'numpad_enter': PADENTER,
    'numpad_-': PADMINUS,
    'numpad_.': PADPERIOD,
    'numpad_+': PADPLUSKEY,
    'numpad_/': PADSLASHKEY,
    'page_down': PAGEDOWNKEY,
    'page_up': PAGEUPKEY,
    'pause': PAUSEKEY,
    #'': QFULL,
    #'': QUOTEKEY, # check this!
    #'': Q_FIRSTTIME,
    #'': RAWKEYBD,
    #'': REDRAW,
    'enter': RETKEY,
    'right_alt': RIGHTALTKEY,
    'right_arrow': RIGHTARROWKEY,
    #'': RIGHTBRACKETKEY, # which bracket?
    'right_ctrl': RIGHTCTRLKEY,
    'right_mouse': RIGHTMOUSE,
    'right_shift': RIGHTSHIFTKEY,
    'space': SPACEKEY,
    'tab': TABKEY,
    'up_arrow': UPARROWKEY,
    'mouse_wheel_down': WHEELDOWNMOUSE,
    'mouse_wheel_up': WHEELUPMOUSE,
    #'': WINCLOSE,
    #'': WINFREEZE,
    #'': WINQUIT,
    #'': WINTHAW,
}
